"""Known first-slice conversions. Do not invent names beyond original identifiers."""

from __future__ import annotations

TEST_SKELETONS = [
    {
        "asset_id": "player_boy_1",
        "skeleton": "cKF_bs_r_boy_1",
        "output": "characters/player/boy_1.glb",
        "animations": [
            "cKF_ba_r_ply_1_wait1",
            "cKF_ba_r_ply_1_walk1",
            "cKF_ba_r_ply_1_run1",
            "cKF_ba_r_ply_1_dash1",
            "cKF_ba_r_ply_1_axe1",
            "cKF_ba_r_ply_1_axe_swing1",
            "cKF_ba_r_ply_1_pickup1",
            "cKF_ba_r_ply_1_dig1",
            "cKF_ba_r_ply_1_shake1",
            "cKF_ba_r_ply_1_net_swing1",
            "cKF_ba_r_ply_1_sao_swing1",
            "cKF_ba_r_ply_1_kamae_wait_m1",
        ],
        "confident_name": True,
    },
    {
        "asset_id": "villager_cat_1",
        "skeleton": "cKF_bs_r_cat_1",
        "output": "characters/villagers/cat_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "villager_xct_1",
        "skeleton": "cKF_bs_r_xct_1",
        "output": "characters/villagers/xct_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "villager_kab_1",
        "skeleton": "cKF_bs_r_kab_1",
        "output": "characters/villagers/kab_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "villager_bea_1",
        "skeleton": "cKF_bs_r_bea_1",
        "output": "characters/villagers/bea_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        ## Train door (`ac_train_door`). Clip opens when Rover enters / exits.
        "asset_id": "obj_romtrain_door",
        "skeleton": "cKF_bs_r_obj_romtrain_door",
        "output": "environment/obj_romtrain_door.glb",
        "animations": ["cKF_ba_r_obj_romtrain_door"],
        "confident_name": True,
    },
    {
        "asset_id": "item_tol_net_1",
        "skeleton": "cKF_bs_r_tol_net_1",
        "output": "items/tol_net_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "item_tol_sao_1",
        "skeleton": "cKF_bs_r_tol_sao_1",
        "output": "items/tol_sao_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "item_tol_keitai_1",
        "skeleton": "cKF_bs_r_tol_keitai_1",
        "output": "items/tol_keitai_1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "item_tol_kaza1",
        "skeleton": "cKF_bs_r_tol_kaza1",
        "output": "items/tol_kaza1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "item_tol_balloon1",
        "skeleton": "cKF_bs_r_tol_balloon1",
        "output": "items/tol_balloon1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "furniture_int_kon_redclock",
        "skeleton": "cKF_bs_r_int_kon_redclock",
        "output": "furniture/int_kon_redclock.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "furniture_int_sum_blue_clk",
        "skeleton": "cKF_bs_r_int_sum_blue_clk",
        "output": "furniture/int_sum_blue_clk.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "furniture_int_kob_locker1",
        "skeleton": "cKF_bs_r_int_kob_locker1",
        "output": "furniture/int_kob_locker1.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "furniture_int_nog_tri_chest01",
        "skeleton": "cKF_bs_r_int_nog_tri_chest01",
        "output": "furniture/int_nog_tri_chest01.glb",
        "animations": [],
        "confident_name": True,
    },
    {
        "asset_id": "furniture_int_sum_log_chest01",
        "skeleton": "cKF_bs_r_int_sum_log_chest01",
        "output": "furniture/int_sum_log_chest01.glb",
        "animations": [],
        "confident_name": True,
    },
]

# Static Gfx models (no cKF skeleton). Paths keep original identifiers.
TEST_STATIC = [
    {
        ## Train car interior (`rom_train_in`). OPA + XLU glass/lights.
        "asset_id": "rom_train_in",
        "vtx": "rom_train_in_v",
        "gfx": ["rom_train_in_model", "rom_train_in_modelT"],
        "output": "environment/interiors/rom_train_in.glb",
        "confident_name": True,
    },
    {
        ## Window scenery beyond the glass (`ac_train_window` / `rom_train_out`).
        "asset_id": "rom_train_out",
        "vtx": "rom_train_out_v",
        "gfx": [
            "rom_train_out_tunnel_model",
            "rom_train_out_bgsky_model",
            "rom_train_out_bgcloud_modelT",
            "rom_train_out_bgtree_modelT",
            "rom_train_out_shineglass_modelT",
        ],
        "output": "environment/interiors/rom_train_out.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_s_tree5",
        "vtx": "obj_s_tree5_v",
        "gfx": ["obj_s_tree5_leafT_gfx_model", "obj_s_tree5_trunkT_gfx_model"],
        "output": "environment/trees/obj_s_tree5.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_s_tree5_apple",
        "vtx": "obj_s_tree5_apple_v",
        "gfx": ["obj_s_tree5_apple_appleT_gfx_model"],
        "output": "environment/trees/obj_s_tree5_apple.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_s_stump5",
        "vtx": "obj_s_stump5_v",
        "gfx": ["obj_stump5T_gfx_model"],
        "output": "environment/trees/obj_s_stump5.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_flower_a",
        "vtx": "obj_flower_a_v",
        "gfx": ["obj_flower_aT_gfx_model"],
        "output": "environment/flowers/obj_flower_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_s_stoneA",
        "vtx": "obj_s_stoneA_v",
        "gfx": ["obj_s_stoneA_gfx_model"],
        "output": "environment/rocks/obj_s_stoneA.glb",
        "confident_name": True,
    },
    {
        ## Field sign board (`ac_sign` / `SIGNBOARD`). Paper is `write_model` + `hakushi_tex`;
        ## wooden frame is `obj_s_kanban_base_tex` on `obj_sign_s_model`.
        "asset_id": "obj_s_kanban",
        "vtx": "obj_s_kanban_v",
        "gfx": ["write_model", "obj_sign_s_model"],
        "output": "environment/obj_s_kanban.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_w_kanban",
        "vtx": "obj_w_kanban_v",
        "gfx": ["write_model", "obj_sign_w_model"],
        "output": "environment/obj_w_kanban.glb",
        "confident_name": True,
    },
    {
        ## Dock `PORT_SIGN` via `ac_reserve` (`obj_*_attentionT_model`), not kanban.
        "asset_id": "obj_s_attention",
        "vtx": "obj_s_attention_v",
        "gfx": ["obj_s_attentionT_model"],
        "output": "environment/obj_s_attention.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_w_attention",
        "vtx": "obj_w_attention_v",
        "gfx": ["obj_w_attentionT_model"],
        "output": "environment/obj_w_attention.glb",
        "confident_name": True,
    },
    {
        "asset_id": "obj_hole0",
        "vtx": "obj_hole0_v",
        "gfx": ["obj_hole0T_gfx_model"],
        "output": "environment/holes/obj_hole0.glb",
        "confident_name": True,
    },
    {
        "asset_id": "tol_axe_1",
        "vtx": "tol_axe_1_v",
        "gfx": ["tol_axe_1_model"],
        "output": "items/tol_axe_1.glb",
        "confident_name": True,
    },
    {
        "asset_id": "tol_scoop_1",
        "vtx": "tol_scoop_1_v",
        "gfx": ["tol_scoop_1_model"],
        "output": "items/tol_scoop_1.glb",
        "confident_name": True,
    },
    {
        # The bobber (uki). `tol_uki_12.c` holds the in-world display list; `tol_uki_1.c`
        # has the inventory-icon variant (`inv_uki_model`) off the same vertex array.
        "asset_id": "tol_uki_1",
        "vtx": "tol_uki_1_v",
        "gfx": ["tol_uki1_model"],
        "output": "items/tol_uki_1.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f01_funa_a",
        "vtx": "act_f01_funa_a_v",
        "gfx": ["act_f01_funa_aT_model"],
        "output": "creatures/fish/act_f01_funa_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f01_funa_b",
        "vtx": "act_f01_funa_b_v",
        "gfx": ["act_f01_funa_bT_model"],
        "output": "creatures/fish/act_f01_funa_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f02_hera_a",
        "vtx": "act_f02_hera_a_v",
        "gfx": ["act_f02_hera_aT_model"],
        "output": "creatures/fish/act_f02_hera_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f02_hera_b",
        "vtx": "act_f02_hera_b_v",
        "gfx": ["act_f02_hera_bT_model"],
        "output": "creatures/fish/act_f02_hera_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f03_koi_a",
        "vtx": "act_f03_koi_a_v",
        "gfx": ["act_f03_koi_aT_model"],
        "output": "creatures/fish/act_f03_koi_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f03_koi_b",
        "vtx": "act_f03_koi_b_v",
        "gfx": ["act_f03_koi_bT_model"],
        "output": "creatures/fish/act_f03_koi_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f04_nisiki_a",
        "vtx": "act_f04_nisiki_a_v",
        "gfx": ["act_f04_nisiki_aT_model"],
        "output": "creatures/fish/act_f04_nisiki_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f04_nisiki_b",
        "vtx": "act_f04_nisiki_b_v",
        "gfx": ["act_f04_nisiki_bT_model"],
        "output": "creatures/fish/act_f04_nisiki_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f05_namazu_a",
        "vtx": "act_f05_namazu_a_v",
        "gfx": ["act_f05_namazu_aT_model"],
        "output": "creatures/fish/act_f05_namazu_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f05_namazu_b",
        "vtx": "act_f05_namazu_b_v",
        "gfx": ["act_f05_namazu_bT_model"],
        "output": "creatures/fish/act_f05_namazu_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f06_bass_a",
        "vtx": "act_f06_bass_a_v",
        "gfx": ["act_f06_bass_aT_model"],
        "output": "creatures/fish/act_f06_bass_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f06_bass_b",
        "vtx": "act_f06_bass_b_v",
        "gfx": ["act_f06_bass_bT_model"],
        "output": "creatures/fish/act_f06_bass_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f07_bassm_a",
        "vtx": "act_f07_bassm_a_v",
        "gfx": ["act_f07_bassm_aT_model"],
        "output": "creatures/fish/act_f07_bassm_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f07_bassm_b",
        "vtx": "act_f07_bassm_b_v",
        "gfx": ["act_f07_bassm_bT_model"],
        "output": "creatures/fish/act_f07_bassm_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f08_bassl_a",
        "vtx": "act_f08_bassl_a_v",
        "gfx": ["act_f08_bassl_aT_model"],
        "output": "creatures/fish/act_f08_bassl_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f08_bassl_b",
        "vtx": "act_f08_bassl_b_v",
        "gfx": ["act_f08_bassl_bT_model"],
        "output": "creatures/fish/act_f08_bassl_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f09_gill_a",
        "vtx": "act_f09_gill_a_v",
        "gfx": ["act_f09_gill_aT_model"],
        "output": "creatures/fish/act_f09_gill_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f09_gill_b",
        "vtx": "act_f09_gill_b_v",
        "gfx": ["act_f09_gill_bT_model"],
        "output": "creatures/fish/act_f09_gill_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f10_oonamazu_a",
        "vtx": "act_f10_oonamazu_a_v",
        "gfx": ["act_f10_oonamazu_aT_model"],
        "output": "creatures/fish/act_f10_oonamazu_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f10_oonamazu_b",
        "vtx": "act_f10_oonamazu_b_v",
        "gfx": ["act_f10_oonamazu_bT_model"],
        "output": "creatures/fish/act_f10_oonamazu_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f11_raigyo_a",
        "vtx": "act_f11_raigyo_a_v",
        "gfx": ["act_f11_raigyo_aT_model"],
        "output": "creatures/fish/act_f11_raigyo_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f11_raigyo_b",
        "vtx": "act_f11_raigyo_b_v",
        "gfx": ["act_f11_raigyo_bT_model"],
        "output": "creatures/fish/act_f11_raigyo_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f12_nigoi_a",
        "vtx": "act_f12_nigoi_a_v",
        "gfx": ["act_f12_nigoi_aT_model"],
        "output": "creatures/fish/act_f12_nigoi_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f12_nigoi_b",
        "vtx": "act_f12_nigoi_b_v",
        "gfx": ["act_f12_nigoi_bT_model"],
        "output": "creatures/fish/act_f12_nigoi_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f13_ugui_a",
        "vtx": "act_f13_ugui_a_v",
        "gfx": ["act_f13_ugui_aT_model"],
        "output": "creatures/fish/act_f13_ugui_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f13_ugui_b",
        "vtx": "act_f13_ugui_b_v",
        "gfx": ["act_f13_ugui_bT_model"],
        "output": "creatures/fish/act_f13_ugui_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f14_oikawa_a",
        "vtx": "act_f14_oikawa_a_v",
        "gfx": ["act_f14_oikawa_aT_model"],
        "output": "creatures/fish/act_f14_oikawa_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f14_oikawa_b",
        "vtx": "act_f14_oikawa_b_v",
        "gfx": ["act_f14_oikawa_bT_model"],
        "output": "creatures/fish/act_f14_oikawa_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f15_tanago_a",
        "vtx": "act_f15_tanago_a_v",
        "gfx": ["act_f15_tanago_aT_model"],
        "output": "creatures/fish/act_f15_tanago_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f15_tanago_b",
        "vtx": "act_f15_tanago_b_v",
        "gfx": ["act_f15_tanago_bT_model"],
        "output": "creatures/fish/act_f15_tanago_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f16_dojyo_a",
        "vtx": "act_f16_dojyo_a_v",
        "gfx": ["act_f16_dojyo_aT_model"],
        "output": "creatures/fish/act_f16_dojyo_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f16_dojyo_b",
        "vtx": "act_f16_dojyo_b_v",
        "gfx": ["act_f16_dojyo_bT_model"],
        "output": "creatures/fish/act_f16_dojyo_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f17_wakasagi_a",
        "vtx": "act_f17_wakasagi_a_v",
        "gfx": ["act_f17_wakasagi_aT_model"],
        "output": "creatures/fish/act_f17_wakasagi_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f17_wakasagi_b",
        "vtx": "act_f17_wakasagi_b_v",
        "gfx": ["act_f17_wakasagi_bT_model"],
        "output": "creatures/fish/act_f17_wakasagi_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f18_ayu_a",
        "vtx": "act_f18_ayu_a_v",
        "gfx": ["act_f18_ayu_aT_model"],
        "output": "creatures/fish/act_f18_ayu_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f18_ayu_b",
        "vtx": "act_f18_ayu_b_v",
        "gfx": ["act_f18_ayu_bT_model"],
        "output": "creatures/fish/act_f18_ayu_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f19_yamame_a",
        "vtx": "act_f19_yamame_a_v",
        "gfx": ["act_f19_yamame_aT_model"],
        "output": "creatures/fish/act_f19_yamame_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f19_yamame_b",
        "vtx": "act_f19_yamame_b_v",
        "gfx": ["act_f19_yamame_bT_model"],
        "output": "creatures/fish/act_f19_yamame_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f20_iwana_a",
        "vtx": "act_f20_iwana_a_v",
        "gfx": ["act_f20_iwana_aT_model"],
        "output": "creatures/fish/act_f20_iwana_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f20_iwana_b",
        "vtx": "act_f20_iwana_b_v",
        "gfx": ["act_f20_iwana_bT_model"],
        "output": "creatures/fish/act_f20_iwana_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f21_niji_a",
        "vtx": "act_f21_niji_a_v",
        "gfx": ["act_f21_niji_aT_model"],
        "output": "creatures/fish/act_f21_niji_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f21_niji_b",
        "vtx": "act_f21_niji_b_v",
        "gfx": ["act_f21_niji_bT_model"],
        "output": "creatures/fish/act_f21_niji_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f22_ito_a",
        "vtx": "act_f22_ito_a_v",
        "gfx": ["act_f22_ito_aT_model"],
        "output": "creatures/fish/act_f22_ito_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f22_ito_b",
        "vtx": "act_f22_ito_b_v",
        "gfx": ["act_f22_ito_bT_model"],
        "output": "creatures/fish/act_f22_ito_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f23_sake_a",
        "vtx": "act_f23_sake_a_v",
        "gfx": ["act_f23_sake_aT_model"],
        "output": "creatures/fish/act_f23_sake_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f23_sake_b",
        "vtx": "act_f23_sake_b_v",
        "gfx": ["act_f23_sake_bT_model"],
        "output": "creatures/fish/act_f23_sake_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f24_kingyo_a",
        "vtx": "act_f24_kingyo_a_v",
        "gfx": ["act_f24_kingyo_aT_model"],
        "output": "creatures/fish/act_f24_kingyo_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f24_kingyo_b",
        "vtx": "act_f24_kingyo_b_v",
        "gfx": ["act_f24_kingyo_bT_model"],
        "output": "creatures/fish/act_f24_kingyo_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f25_pirania_a",
        "vtx": "act_f25_pirania_a_v",
        "gfx": ["act_f25_pirania_aT_model"],
        "output": "creatures/fish/act_f25_pirania_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f25_pirania_b",
        "vtx": "act_f25_pirania_b_v",
        "gfx": ["act_f25_pirania_bT_model"],
        "output": "creatures/fish/act_f25_pirania_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f26_aroana_a",
        "vtx": "act_f26_aroana_a_v",
        "gfx": ["act_f26_aroana_aT_model"],
        "output": "creatures/fish/act_f26_aroana_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f26_aroana_b",
        "vtx": "act_f26_aroana_b_v",
        "gfx": ["act_f26_aroana_bT_model"],
        "output": "creatures/fish/act_f26_aroana_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f27_unagi_a",
        "vtx": "act_f27_unagi_a_v",
        "gfx": ["act_f27_unagi_aT_model"],
        "output": "creatures/fish/act_f27_unagi_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f27_unagi_b",
        "vtx": "act_f27_unagi_b_v",
        "gfx": ["act_f27_unagi_bT_model"],
        "output": "creatures/fish/act_f27_unagi_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f28_donko_a",
        "vtx": "act_f28_donko_a_v",
        "gfx": ["act_f28_donko_aT_model"],
        "output": "creatures/fish/act_f28_donko_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f28_donko_b",
        "vtx": "act_f28_donko_b_v",
        "gfx": ["act_f28_donko_bT_model"],
        "output": "creatures/fish/act_f28_donko_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f29_angel_a",
        "vtx": "act_f29_angel_a_v",
        "gfx": ["act_f29_angel_aT_model"],
        "output": "creatures/fish/act_f29_angel_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f29_angel_b",
        "vtx": "act_f29_angel_b_v",
        "gfx": ["act_f29_angel_bT_model"],
        "output": "creatures/fish/act_f29_angel_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f30_gupi_a",
        "vtx": "act_f30_gupi_a_v",
        "gfx": ["act_f30_gupi_aT_model"],
        "output": "creatures/fish/act_f30_gupi_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f30_gupi_b",
        "vtx": "act_f30_gupi_b_v",
        "gfx": ["act_f30_gupi_bT_model"],
        "output": "creatures/fish/act_f30_gupi_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f31_demekin_a",
        "vtx": "act_f31_demekin_a_v",
        "gfx": ["act_f31_demekin_aT_model"],
        "output": "creatures/fish/act_f31_demekin_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f31_demekin_b",
        "vtx": "act_f31_demekin_b_v",
        "gfx": ["act_f31_demekin_bT_model"],
        "output": "creatures/fish/act_f31_demekin_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f32_kaseki_a",
        "vtx": "act_f32_kaseki_a_v",
        "gfx": ["act_f32_kaseki_aT_model"],
        "output": "creatures/fish/act_f32_kaseki_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f32_kaseki_b",
        "vtx": "act_f32_kaseki_b_v",
        "gfx": ["act_f32_kasekiT_model"],
        "output": "creatures/fish/act_f32_kaseki_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f35_zarigani_a",
        "vtx": "act_f35_zarigani_a_v",
        "gfx": ["act_f35_zarigani_aT_model"],
        "output": "creatures/fish/act_f35_zarigani_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f35_zarigani_b",
        "vtx": "act_f35_zarigani_b_v",
        "gfx": ["act_f35_zarigani_bT_model"],
        "output": "creatures/fish/act_f35_zarigani_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f36_kaeru_a",
        "vtx": "act_f36_kaeru_a_v",
        "gfx": ["act_f36_kaeru_aT_model"],
        "output": "creatures/fish/act_f36_kaeru_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f36_kaeru_b",
        "vtx": "act_f36_kaeru_b_v",
        "gfx": ["act_f36_kaeru_bT_model"],
        "output": "creatures/fish/act_f36_kaeru_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f33_medaka_a",
        "vtx": "act_f33_medaka_a_v",
        "gfx": ["act_f33_medaka_aT_model"],
        "output": "creatures/fish/act_f33_medaka_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f33_medaka_b",
        "vtx": "act_f33_medaka_b_v",
        "gfx": ["act_f33_medaka_bT_model"],
        "output": "creatures/fish/act_f33_medaka_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f37_kurage_a",
        "vtx": "act_f37_kurage_a_v",
        "gfx": ["act_f37_kurage_aT_model"],
        "output": "creatures/fish/act_f37_kurage_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f37_kurage_b",
        "vtx": "act_f37_kurage_b_v",
        "gfx": ["act_f37_kurage_bT_model"],
        "output": "creatures/fish/act_f37_kurage_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f38_suzuki_a",
        "vtx": "act_f38_suzuki_a_v",
        "gfx": ["act_f38_suzuki_aT_model"],
        "output": "creatures/fish/act_f38_suzuki_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f38_suzuki_b",
        "vtx": "act_f38_suzuki_b_v",
        "gfx": ["act_f38_suzuki_bT_model"],
        "output": "creatures/fish/act_f38_suzuki_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f39_tai_a",
        "vtx": "act_f39_tai_a_v",
        "gfx": ["act_f39_tai_aT_model"],
        "output": "creatures/fish/act_f39_tai_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f39_tai_b",
        "vtx": "act_f39_tai_b_v",
        "gfx": ["act_f39_tai_bT_model"],
        "output": "creatures/fish/act_f39_tai_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f40_isidai_a",
        "vtx": "act_f40_isidai_a_v",
        "gfx": ["act_f40_isidai_aT_model"],
        "output": "creatures/fish/act_f40_isidai_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f40_isidai_b",
        "vtx": "act_f40_isidai_b_v",
        "gfx": ["act_f40_isidai_bT_model"],
        "output": "creatures/fish/act_f40_isidai_b.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f34_piraluku_a",
        "vtx": "act_f34_piraluku_a_v",
        "gfx": ["act_f34_piraluku_aT_model"],
        "output": "creatures/fish/act_f34_piraluku_a.glb",
        "confident_name": True,
    },
    {
        "asset_id": "act_f34_piraluku_b",
        "vtx": "act_f34_piraluku_b_v",
        "gfx": ["act_f34_piraluku_bT_model"],
        "output": "creatures/fish/act_f34_piraluku_b.glb",
        "confident_name": True,
    },
]

# Field / held insect models (`act_m_*`). Pose `a`/`b` map to `aINS_*_dl` slots
# `(pose<<1)` / `+1` on shared `{base}_v` (not fish-style `{base}_a_v`). Each
# pose GLB includes both DLs drawn that frame. Firefly uses `act_m_genji2_*`.
_BUG_MODEL_BASES = [
    "act_m_monshiro",
    "act_m_monki",
    "act_m_kiageha",
    "act_m_ohmurasaki",
    "act_m_minmin",
    "act_m_tukutuku",
    "act_m_higurashi",
    "act_m_abura",
    "act_m_hachi",
    "act_m_shiokara",
    "act_m_akiakane",
    "act_m_ginyanma",
    "act_m_oniyanma",
    "act_m_syouryou",
    "act_m_tonosama",
    "act_m_koorogi",
    "act_m_kirigirisu",
    "act_m_suzumushi",
    "act_m_matumushi",
    "act_m_kanabun",
    "act_m_kabuto",
    "act_m_hirata",
    "act_m_tamamushi",
    "act_m_gomadara",
    "act_m_tentou",
    "act_m_nanahoshi",
    "act_m_kamakiri",
    "act_m_genji",
    "act_m_danna",
    "act_m_nokogiri",
    "act_m_miyama",
    "act_m_okuwa",
    "act_m_maimai",
    "act_m_kera",
    "act_m_amenbo",
    "act_m_mino",
    "act_m_dango",
    "act_m_kumo",
    "act_m_ari",
    "act_m_ka",
]

# `aINS_*_dl` pose pairs from `ac_insect_data.c_inc`. Draw submits indices
# `(pose<<1)` and `(pose<<1)+1` every frame, so each Godot pose GLB must include
# both display lists (deduped). Missing bases use `{base}1T` / `{base}2T`.
_BUG_POSE_GFX: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "act_m_minmin": (
        ("act_m_minmin1_1T_model", "act_m_minmin1_2T_model"),
        ("act_m_minmin1_1T_model", "act_m_minmin2_2T_model"),
    ),
    "act_m_tukutuku": (
        ("act_m_tukutuku1_1T_model", "act_m_tukutuku1_2T_model"),
        ("act_m_tukutuku1_1T_model", "act_m_tukutuku2_2T_model"),
    ),
    "act_m_higurashi": (
        ("act_m_higurashi1_1T_model", "act_m_higurashi1_2T_model"),
        ("act_m_higurashi1_1T_model", "act_m_higurashi2_2T_model"),
    ),
    "act_m_abura": (
        ("act_m_abura1_1T_model", "act_m_abura1_2T_model"),
        ("act_m_abura1_1T_model", "act_m_abura2_2T_model"),
    ),
    "act_m_hachi": (
        ("act_m_hachi1_1T_model", "act_m_hachi1_2T_model"),
        ("act_m_hachi1_1T_model", "act_m_hachi2_2T_model"),
    ),
    "act_m_shiokara": (
        ("act_m_shiokara1_1T_model", "act_m_shiokara1_2T_model"),
        ("act_m_shiokara1_1T_model", "act_m_shiokara2_2T_model"),
    ),
    "act_m_akiakane": (
        ("act_m_akiakane1_1T_model", "act_m_akiakane1_2T_model"),
        ("act_m_akiakane1_1T_model", "act_m_akiakane2_2T_model"),
    ),
    "act_m_ginyanma": (
        ("act_m_ginyanma1_1T_model", "act_m_ginyanma1_2T_model"),
        ("act_m_ginyanma1_1T_model", "act_m_ginyanma2_2T_model"),
    ),
    "act_m_oniyanma": (
        ("act_m_oniyanma1_1T_model", "act_m_oniyanma1_2T_model"),
        ("act_m_oniyanma1_1T_model", "act_m_oniyanma2_2T_model"),
    ),
    "act_m_syouryou": (
        ("act_m_syouryou1T_model",),
        ("act_m_syouryou1T_model", "act_m_syouryou2_2T_model"),
    ),
    "act_m_tonosama": (
        ("act_m_tonosama1T_model",),
        ("act_m_tonosama1T_model", "act_m_tonosama2_2T_model"),
    ),
    "act_m_koorogi": (("act_m_koorogi1T_model",), ("act_m_koorogi1T_model",)),
    "act_m_kirigirisu": (
        ("act_m_kirigirisu1T_model",),
        ("act_m_kirigirisu1T_model", "act_m_kirigirisu2_2T_model"),
    ),
    "act_m_suzumushi": (
        ("act_m_suzumushi1T_model",),
        ("act_m_suzumushi1T_model", "act_m_suzumushi2_2T_model"),
    ),
    "act_m_matumushi": (("act_m_matumushi1T_model",), ("act_m_matumushi1T_model",)),
    "act_m_kamakiri": (
        ("act_m_kamakiri1T_model",),
        ("act_m_kamakiri1T_model", "act_m_kamakiri2_2T_model"),
    ),
    "act_m_genji": (
        ("act_m_genji2_a_model", "act_m_genji2_b_model"),
        ("act_m_genji2_c_model", "act_m_genji2_d_model"),
    ),
    "act_m_maimai": (("act_m_maimaiT_model",), ("act_m_maimaiT_model",)),
    "act_m_kera": (("act_m_keraT_model",), ("act_m_keraT_model",)),
    "act_m_mino": (
        ("act_m_mino1_1T_model",),
        ("act_m_mino1_1T_model", "act_m_mino2T_model"),
    ),
    "act_m_kumo": (
        ("act_m_kumo1_2T_model",),
        ("act_m_kumo1_1T_model", "act_m_kumo2T_model"),
    ),
    "act_m_ari": (("act_m_ariT_model",), ("act_m_ariT_model",)),
    "act_m_ka": (
        ("act_m_ka1T_model", "act_m_ka2_2T_model"),
        ("act_m_ka1T_model", "act_m_ka2_1T_model"),
    ),
    "act_m_amenbo": (
        ("act_m_amenbo1T_model",),
        ("act_m_amenbo1T_model", "act_m_amenbo2T_model"),
    ),
    "act_m_dango": (("act_m_dango2T_model",), ("act_m_dango1T_model",)),
}


def _bug_vtx(base: str) -> str:
    if base == "act_m_genji":
        return "act_m_genji2_v"
    return f"{base}_v"


def _bug_pose_gfx(base: str) -> tuple[list[str], list[str]]:
    if base in _BUG_POSE_GFX:
        a_gfx, b_gfx = _BUG_POSE_GFX[base]
        return (list(a_gfx), list(b_gfx))
    return ([f"{base}1T_model"], [f"{base}2T_model"])


for _base in _BUG_MODEL_BASES:
    _a_gfx, _b_gfx = _bug_pose_gfx(_base)
    _vtx = _bug_vtx(_base)
    for _pose, _gfx in (("a", _a_gfx), ("b", _b_gfx)):
        TEST_STATIC.append(
            {
                "asset_id": f"{_base}_{_pose}",
                "vtx": _vtx,
                "gfx": _gfx,
                "output": f"creatures/bug/{_base}_{_pose}.glb",
                "confident_name": True,
            }
        )

# Standalone BTI files from forest_2nd. Keep original filenames; do not invent roles.
TEST_BTI = [
    ("forest_2nd/data/boy1.bti", "ui/boy1.png"),
    ("forest_2nd/data/boy2.bti", "ui/boy2.png"),
    ("forest_2nd/data/girl1.bti", "ui/girl1.png"),
    ("forest_2nd/data/title.bti", "ui/title.png"),
    ("forest_2nd/data/mura_spring.bti", "ui/mura_spring.png"),
    ("forest_2nd/data/mura_summer.bti", "ui/mura_summer.png"),
    ("forest_2nd/data/mura_fall.bti", "ui/mura_fall.png"),
    ("forest_2nd/data/mura_winter.bti", "ui/mura_winter.png"),
    ("forest_2nd/data/eki1.bti", "ui/eki1.png"),
]
