class_name BugSpawnScheduler
extends RefCounted

## `aSOI_insect_set` — the per-acre-entry insect spawn decision.
##
## `BugSpawnTable` holds the raw `l_insect_month[month][term]` weights (from decomp,
## generated by `tools/generate_bugs.py`). This layer adds the parts of the decomp
## scheduler that live in code rather than data:
##  - the 5-day cross-month blend (`aSOI_ins_chk_term_info` / `aSOI_ins_make_range_data`)
##  - the always-on ant / cockroach spawn additions (`aSOI_ins_add_range_info`)
##  - `env_rate` weighting by town rank + the "< 100 total ⇒ chance of no spawn" gate
##    and the candy / trash override (`aSOI_ins_get_idx` / `aSOI_ins_limit_insect_data`)
##
## Acre-feature feasibility and the live-unit pick stay in `BugHabitats`, which
## already mirrors `aSOI_chk_live_area_data` / `aSOI_make_live_ut`.

## `aSOI_ins_add_range_info` — {type_index, spawn_area, weight}. Always appended.
const ADDITIONS := [
	{"type_index": 38, "spawn_area": 8, "weight": 1.0},   ## ANT on candy
	{"type_index": 38, "spawn_area": 9, "weight": 1.0},   ## ANT on trash
	{"type_index": 28, "spawn_area": 9, "weight": 1.0},   ## COCKROACH on trash
]
## `env_rate_table[mFAs_FIELDRANK_*]` — town-environment weighting.
const ENV_RATE := [0.5, 0.75, 0.875, 1.0, 1.0, 1.0, 1.0]
## `aSOI_ins_chk_term_info` `rate[]` — previous-month weight over the transition.
const PREV_RATE := [1.0 / 6.0, 2.0 / 6.0, 3.0 / 6.0, 4.0 / 6.0, 5.0 / 6.0]

const AREA_ON_CANDY := 8
const AREA_ON_TRASH := 9
const AREA_FLYING := 3
const AREA_ON_FLOWER := 1
const AREA_FLYING_NEAR_FLOWERS := 12


## Town field rank (`mFAs_GetFieldRank`). No town-assessment system yet → rank 3
## (`env_rate` 1.0). Hook here when one lands.
static func field_rank() -> int:
	return 3


static func env_rate() -> float:
	return ENV_RATE[clampi(field_rank(), 0, ENV_RATE.size() - 1)]


## `aSOI_ins_chk_term_info`: the previous month's table and its blend weight for
## today. Returns {prev_month, prev_rate} — prev_rate 0 outside the transition.
static func term_blend(rng: RandomNumberGenerator) -> Dictionary:
	var month: int = Clock.month
	var prev_month: int = 12 if month == 1 else month - 1
	if Game.insect_term_month != month:
		Game.insect_term_month = month
		Game.insect_term_offset = (rng.randi_range(0, 5) if rng != null else 0)
	var di: int = Clock.day - 1 - Game.insect_term_offset
	var prev_rate: float = 0.0
	if di >= 0 and di < PREV_RATE.size():
		prev_rate = PREV_RATE[di]
	return {"prev_month": prev_month, "prev_rate": prev_rate}


## `aSOI_ins_make_range_data` (town): blended month/term table + the 3 additions.
static func build_pool(rng: RandomNumberGenerator) -> Array[BugSpawnEntry]:
	var hour: int = Clock.hour
	var out: Array[BugSpawnEntry] = []
	var blend: Dictionary = term_blend(rng)
	var prev_rate: float = float(blend["prev_rate"])
	for e: BugSpawnEntry in BugSpawnTable.entries_for(Clock.month, hour):
		var c := BugSpawnEntry.new()
		c.type_index = e.type_index
		c.spawn_area = e.spawn_area
		c.weight = e.weight * (1.0 - prev_rate)
		out.append(c)
	if prev_rate > 0.0:
		for e: BugSpawnEntry in BugSpawnTable.entries_for(int(blend["prev_month"]), hour):
			var c := BugSpawnEntry.new()
			c.type_index = e.type_index
			c.spawn_area = e.spawn_area
			c.weight = e.weight * prev_rate
			out.append(c)
	for add: Dictionary in ADDITIONS:
		var c := BugSpawnEntry.new()
		c.type_index = int(add["type_index"])
		c.spawn_area = int(add["spawn_area"])
		c.weight = float(add["weight"])
		out.append(c)
	return out


## `aSOI_ins_decide_insect` + `aSOI_ins_get_idx`. Returns the chosen entry (spawn
## area already resolved past `FLYING_NEAR_FLOWERS_OR_AROUND`), or null (no spawn).
static func decide(
	pool: Array[BugSpawnEntry],
	layout: WorldData,
	grid: WorldGrid,
	acre: Vector2i,
	raining: bool,
	occupied: Callable,
	rng: RandomNumberGenerator
) -> BugSpawnEntry:
	## Feasibility: zero the weight of any entry whose spawn area the acre cannot host.
	var feasible: Dictionary = {}   ## spawn_area -> bool
	var candy: bool = false
	var trash: bool = false
	for entry: BugSpawnEntry in pool:
		var area: int = entry.spawn_area
		if not feasible.has(area):
			feasible[area] = BugHabitats.has_spawn_area(area, layout, grid, acre, occupied, raining)
			if bool(feasible[area]):
				if area == AREA_ON_CANDY:
					candy = true
				elif area == AREA_ON_TRASH:
					trash = true
	## Candy / spoiled-turnip present → only those entries can spawn.
	var live: Array[BugSpawnEntry] = []
	for entry: BugSpawnEntry in pool:
		if not bool(feasible.get(entry.spawn_area, false)):
			continue
		if (candy or trash) and entry.spawn_area != AREA_ON_CANDY and entry.spawn_area != AREA_ON_TRASH:
			continue
		live.append(entry)
	if live.is_empty():
		return null

	var on_bait: bool = candy or trash
	var rate: float = 1.0 if on_bait else env_rate()
	var total: float = 0.0
	for entry: BugSpawnEntry in live:
		total += entry.weight
	if total <= 0.0:
		return null
	var sel: float = rng.randf() * (total if (on_bait or total > 100.0) else 100.0)
	for entry: BugSpawnEntry in live:
		sel -= entry.weight * rate
		if sel < 0.0:
			return _resolve(entry, layout, grid, acre)
	return null


static func _resolve(
	entry: BugSpawnEntry, layout: WorldData, grid: WorldGrid, acre: Vector2i
) -> BugSpawnEntry:
	if entry.spawn_area != AREA_FLYING_NEAR_FLOWERS:
		return entry
	## `aSOI_ins_change_how_to_make`: flowers if any, else flying.
	var out := BugSpawnEntry.new()
	out.type_index = entry.type_index
	out.weight = entry.weight
	out.spawn_area = (
		AREA_ON_FLOWER
		if not BugHabitats.sites_for_spawn_area(
			AREA_ON_FLOWER, layout, grid, acre, func(_c: Vector2i) -> bool: return false, false
		).is_empty()
		else AREA_FLYING
	)
	return out
