class_name BugSpawnTable
extends RefCounted

## Term-accurate insect spawn weights from `ac_set_ovl_insect.c`.
## Generated by `tools/generate_bugs.py` into `data/bugs/spawn_table.json`.

const TABLE_PATH := "res://data/bugs/spawn_table.json"

static var _tables: Dictionary = {}
static var _other: Array = []
static var _loaded: bool = false


static func ensure_loaded() -> void:
	if _loaded:
		return
	_tables.clear()
	_other.clear()
	var file := FileAccess.open(TABLE_PATH, FileAccess.READ)
	if file == null:
		push_warning("BugSpawnTable: missing %s" % TABLE_PATH)
		_loaded = true
		return
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_warning("BugSpawnTable: invalid JSON in %s" % TABLE_PATH)
		_loaded = true
		return
	var tables: Variant = parsed.get("tables", {})
	if typeof(tables) == TYPE_DICTIONARY:
		_tables = tables
	var other: Variant = parsed.get("other", [])
	if typeof(other) == TYPE_ARRAY:
		_other = other
	_loaded = true


static func entries_for(month: int, hour: int) -> Array[BugSpawnEntry]:
	ensure_loaded()
	var term: int = int(BugData.term_for_hour(hour))
	var month_key: String = str(month)
	var term_key: String = str(term)
	var month_tables: Dictionary = _tables.get(month_key, {}) as Dictionary
	var raw: Variant = month_tables.get(term_key, [])
	var out: Array[BugSpawnEntry] = []
	if typeof(raw) == TYPE_ARRAY:
		for item: Variant in raw:
			if typeof(item) != TYPE_DICTIONARY:
				continue
			var entry := BugSpawnEntry.new()
			entry.type_index = int(item.get("type_index", -1))
			entry.spawn_area = int(item.get("spawn_area", -1))
			entry.weight = float(item.get("weight", 0))
			if entry.type_index >= 0 and entry.spawn_area >= 0 and entry.weight > 0.0:
				out.append(entry)
	return out


static func weather_allows(spawn_area: int, raining: bool) -> bool:
	match spawn_area:
		1:
			return not raining
		2:
			return raining
		_:
			return true


static func reload() -> void:
	_loaded = false
	ensure_loaded()
