extends Node
## Bakes every `grd_*` acre GLB into a scene, so an acre is authored data instead of
## a runtime material pass:
##
##   scenes/world/acres/<id>.tscn    Acre root + MeshInstance3D nodes, materials as overrides
##                                   (regenerated by every bake; edit the materials instead)
##
##   assets/generated/environment/acre_scenes/   (gitignored, derived from the disc extract)
##     grids/<id>.tres              AcreGrid (the 16x16 unit table from <id>.col.json)
##     meshes/<id>/<node>.res       geometry only (materials live in the scene)
##     materials/<key>.tres         terrain materials, shared between acres
##     materials/water/<kind>_<key>.tres   river / ocean / splash / wet-sand shaders
##     textures/<hash>.png          every texture, deduplicated by content
##     textures/water/<kind>_<param>_<hash>.png
##
## Replace a water texture by editing the PNG (or swapping the texture on the `.tres`).
## Existing meshes, materials, textures and grids are never overwritten, so hand edits to
## them survive a re-bake; delete a file to regenerate it. The scenes are rewritten.
##
## New PNGs must be imported by the editor before a material can reference them, hence
## two passes (`tools/bake_acre_scenes.sh` runs both with the import in between):
##   godot --headless --path . --import              (GLBs must be imported first)
##   godot --headless --path . res://tools/bake_acre_scenes.tscn -- textures [id ...]
##   godot --headless --path . --import
##   godot --headless --path . res://tools/bake_acre_scenes.tscn -- scenes [id ...]
## It runs as a scene, not `--script`, because the runtime classes it reuses need the
## project autoloads (`Clock`).

const ACRES_DIR := "res://assets/generated/environment/acres/"
const OUT_DIR := "res://assets/generated/environment/acre_scenes/"
const SCENE_DIR := "res://scenes/world/acres/"
const WATER_KINDS: Dictionary = {
	"river_water": "river",
	"ocean_water": "ocean",
	"splash_water": "splash",
	"waterfall_water": "waterfall",
	"beach_wet": "beach_wet",
}
## Sidecar params the pipeline uses for pixel-art PNGs (`godot_import.PNG_PARAMS`).
const PNG_IMPORT_PARAMS := """[remap]

importer="texture"
type="CompressedTexture2D"

[deps]

source_file="%s"

[params]

compress/mode=0
mipmaps/generate=false
process/fix_alpha_border=false
detect_3d/compress_to=0
"""

var _write_textures := false
var _tex_cache: Dictionary = {}
var _material_cache: Dictionary = {}
var _written := {"png": 0, "material": 0, "mesh": 0, "scene": 0, "grid": 0}


func _ready() -> void:
	var args: PackedStringArray = OS.get_cmdline_user_args()
	if args.is_empty() or not args[0] in ["textures", "scenes"]:
		push_error("usage: -- textures|scenes [acre_id ...]")
		get_tree().quit(2)
		return
	_write_textures = args[0] == "textures"
	var only: PackedStringArray = args.slice(1)
	var ids: PackedStringArray = _acre_ids(only)
	var failed := 0
	for id: String in ids:
		if not _bake(id):
			failed += 1
	print("%s: %d acres, %s, %d failed" % [args[0], ids.size(), _written, failed])
	get_tree().quit(1 if failed > 0 else 0)


func _acre_ids(only: PackedStringArray) -> PackedStringArray:
	var ids := PackedStringArray()
	for file: String in DirAccess.get_files_at(ACRES_DIR):
		if file.begins_with("grd_") and file.ends_with(".glb"):
			var id: String = file.get_basename()
			if FieldCatalog.is_interior_shell_visual(StringName(id)):
				continue
			if only.is_empty() or only.has(id):
				ids.append(id)
	ids.sort()
	return ids


func _bake(id: String) -> bool:
	var packed := load(ACRES_DIR + id + ".glb") as PackedScene
	if packed == null:
		push_error("%s: GLB failed to load" % id)
		return false
	var model: Node = packed.instantiate()
	var pivot := Node3D.new()
	pivot.add_child(model)
	## The same material pass a GLB acre gets at runtime, run once and saved.
	VisualWaterMaterials.prepare_acre(pivot, StringName(id))
	var meshes: Array[MeshInstance3D] = []
	_collect_meshes(pivot, meshes)
	for mesh_instance: MeshInstance3D in meshes:
		_stamp_season_roles(mesh_instance)
	var ok := true
	if _write_textures:
		for mesh_instance: MeshInstance3D in meshes:
			for surface: int in _surface_count(mesh_instance):
				_externalize_material(mesh_instance.get_active_material(surface))
	else:
		ok = _write_scene(id, pivot, meshes)
	pivot.free()
	return ok


func _collect_meshes(node: Node, out: Array[MeshInstance3D]) -> void:
	if node is MeshInstance3D and (node as MeshInstance3D).mesh != null:
		out.append(node as MeshInstance3D)
	for child: Node in node.get_children():
		_collect_meshes(child, out)


func _surface_count(mesh_instance: MeshInstance3D) -> int:
	return mesh_instance.mesh.get_surface_count()


## Stamp what the season swap needs, so runtime reads data and not names: the role a
## surface takes from the seasons pack, and the wrap-bake period of its atlas.
func _stamp_season_roles(mesh_instance: MeshInstance3D) -> void:
	for surface: int in _surface_count(mesh_instance):
		var mat: Material = mesh_instance.get_active_material(surface)
		if mat == null:
			continue
		var role: String = FieldCatalog.season_role_for_surface(mesh_instance, surface, mat)
		if role.is_empty():
			continue
		if mat is ShaderMaterial:
			if not mat.has_meta("beach_wet"):
				continue
		elif not mat is StandardMaterial3D:
			continue
		var own: Material = mat.duplicate()
		own.set_meta("field_role", role)
		if own is StandardMaterial3D:
			var std := own as StandardMaterial3D
			if std.albedo_texture != null:
				std.set_meta("atlas_cell", VisualAtlas.infer_tile_size(std.albedo_texture, 0))
		mesh_instance.set_surface_override_material(surface, own)


# ---- scenes ----------------------------------------------------------------------------


func _write_scene(id: String, pivot: Node3D, meshes: Array[MeshInstance3D]) -> bool:
	var root := Acre.new()
	root.name = id
	root.visual_id = StringName(id)
	root.grid = _write_grid(id)
	for source: MeshInstance3D in meshes:
		var node := MeshInstance3D.new()
		node.name = source.name
		node.transform = _relative_transform(source, pivot)
		node.cast_shadow = source.cast_shadow
		node.sorting_offset = source.sorting_offset
		node.mesh = _write_mesh(id, source)
		for surface: int in _surface_count(source):
			node.set_surface_override_material(surface, _externalize_material(source.get_active_material(surface)))
		root.add_child(node)
		node.owner = root
	var scene := PackedScene.new()
	var err: int = scene.pack(root)
	root.free()
	if err != OK:
		push_error("%s: pack failed (%d)" % [id, err])
		return false
	_ensure_dir(SCENE_DIR + id + ".tscn")
	err = ResourceSaver.save(scene, SCENE_DIR + id + ".tscn")
	if err != OK:
		push_error("%s: save failed (%d)" % [id, err])
		return false
	_written["scene"] += 1
	return true


## Transform of `node` in `pivot` space (the tree is not live, so no `global_transform`).
func _relative_transform(node: Node3D, pivot: Node3D) -> Transform3D:
	var xf := Transform3D.IDENTITY
	var current: Node = node
	while current != null and current != pivot:
		if current is Node3D:
			xf = (current as Node3D).transform * xf
		current = current.get_parent()
	return xf


## An acre with a `.col.json` always gets a grid; a filler's has empty `units`, which is
## how `FieldCatalog.acre_for_block_type` knows to skip it.
func _write_grid(id: String) -> AcreGrid:
	var grid: AcreGrid = AcreGrid.from_col_json(id)
	if grid == null:
		return null
	var path: String = FieldCatalog.acre_grid_path(id)
	_ensure_dir(path)
	if ResourceSaver.save(grid, path) != OK:
		push_error("%s: grid save failed" % id)
		return null
	_written["grid"] += 1
	return load(path) as AcreGrid


## Geometry only: the scene's overrides carry every material, so the mesh file holds no
## material (and therefore no embedded texture).
func _write_mesh(id: String, source: MeshInstance3D) -> Mesh:
	var mesh := source.mesh.duplicate() as ArrayMesh
	for surface: int in mesh.get_surface_count():
		mesh.surface_set_material(surface, null)
	var path := "%smeshes/%s/%s.res" % [OUT_DIR, id, source.name]
	_ensure_dir(path)
	ResourceSaver.save(mesh, path)
	_written["mesh"] += 1
	return load(path) as Mesh


# ---- materials & textures ----------------------------------------------------------------


## Returns the material with every texture swapped for an external PNG, saved once under a
## key derived from its content. In the `textures` pass it only writes the PNGs.
func _externalize_material(mat: Material) -> Material:
	if mat == null:
		return null
	var copy: Material = mat.duplicate()
	var water: String = _water_kind(copy)
	for prop_name: String in _texture_properties(copy):
		var tex: Variant = _get_texture(copy, prop_name)
		if tex is Texture2D:
			var prefix := "water/%s_%s" % [water, prop_name.trim_prefix("shader_parameter/")] if not water.is_empty() else ""
			var ext: Texture2D = _externalize_texture(tex as Texture2D, prefix)
			if ext != null:
				_set_texture(copy, prop_name, ext)
	if _write_textures:
		return null
	var key: String = _content_key(copy)
	if _material_cache.has(key):
		return _material_cache[key]
	var path := "%smaterials/%s%s.tres" % [OUT_DIR, "water/%s_" % water if not water.is_empty() else "", key]
	_ensure_dir(path)
	if not FileAccess.file_exists(path):
		ResourceSaver.save(copy, path)
		_written["material"] += 1
	var saved := load(path) as Material
	_material_cache[key] = saved
	return saved


func _water_kind(mat: Material) -> String:
	for meta: String in WATER_KINDS:
		if mat.has_meta(meta):
			return WATER_KINDS[meta]
	return ""


## Property names (StandardMaterial3D) or `shader_parameter/<uniform>` names (ShaderMaterial)
## that can hold a texture.
func _texture_properties(mat: Material) -> PackedStringArray:
	var names := PackedStringArray()
	if mat is ShaderMaterial and (mat as ShaderMaterial).shader != null:
		for uniform: Dictionary in (mat as ShaderMaterial).shader.get_shader_uniform_list():
			if int(uniform["type"]) == TYPE_OBJECT:
				names.append("shader_parameter/" + String(uniform["name"]))
	elif mat is StandardMaterial3D:
		for prop: Dictionary in mat.get_property_list():
			if int(prop["type"]) == TYPE_OBJECT and String(prop["hint_string"]) == "Texture2D":
				names.append(String(prop["name"]))
	return names


func _get_texture(mat: Material, prop_name: String) -> Variant:
	if mat is ShaderMaterial:
		return (mat as ShaderMaterial).get_shader_parameter(prop_name.trim_prefix("shader_parameter/"))
	return mat.get(prop_name)


func _set_texture(mat: Material, prop_name: String, tex: Texture2D) -> void:
	if mat is ShaderMaterial:
		(mat as ShaderMaterial).set_shader_parameter(prop_name.trim_prefix("shader_parameter/"), tex)
	else:
		mat.set(prop_name, tex)


## `prefix` (e.g. `water/river_water1`) names a water layer so it can be found and replaced;
## other textures are named by content hash.
func _externalize_texture(tex: Texture2D, prefix: String) -> Texture2D:
	var img: Image = VisualAtlas.texture_image(tex)
	if img == null:
		push_error("texture has no readable image (%s)" % tex.resource_path)
		return null
	var digest: String = _hash_image(img)
	var path: String = "%stextures/%s.png" % [
		OUT_DIR, "%s_%s" % [prefix, digest.substr(0, 8)] if not prefix.is_empty() else digest.substr(0, 12)
	]
	if _write_textures:
		if not FileAccess.file_exists(path):
			_ensure_dir(path)
			img.save_png(path)
			var sidecar := FileAccess.open(path + ".import", FileAccess.WRITE)
			sidecar.store_string(PNG_IMPORT_PARAMS % path)
			_written["png"] += 1
		return null
	if not _tex_cache.has(path):
		_tex_cache[path] = load(path) as Texture2D
	return _tex_cache[path]


func _hash_image(img: Image) -> String:
	var ctx := HashingContext.new()
	ctx.start(HashingContext.HASH_MD5)
	ctx.update(("%d,%d,%d;" % [img.get_width(), img.get_height(), img.get_format()]).to_utf8_buffer())
	ctx.update(img.get_data())
	return ctx.finish().hex_encode()


## Stable key for a material: its class, stored properties and metadata, with textures
## reduced to their (external) paths.
func _content_key(mat: Material) -> String:
	var dump := {"class": mat.get_class()}
	for prop: Dictionary in mat.get_property_list():
		if int(prop["usage"]) & PROPERTY_USAGE_STORAGE == 0:
			continue
		var value: Variant = mat.get(prop["name"])
		dump[prop["name"]] = value.resource_path if value is Resource else value
	if mat is ShaderMaterial:
		for uniform: Dictionary in (mat as ShaderMaterial).shader.get_shader_uniform_list():
			var value: Variant = (mat as ShaderMaterial).get_shader_parameter(uniform["name"])
			dump["u/" + String(uniform["name"])] = value.resource_path if value is Resource else value
	for meta: StringName in mat.get_meta_list():
		dump["m/" + String(meta)] = mat.get_meta(meta)
	return var_to_str(dump).md5_text().substr(0, 12)


func _ensure_dir(path: String) -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))
