#!/usr/bin/env python3
"""Write data/events/event_map.json from the decomp's event map tables.

`m_event_map_npc_data.c_inc` (`l_event_set_table`) says where each festival's actors stand
inside its acre (shrine / pond / …) and how many residents join in. The JSON keeps the same
shape with readable names:

    {"<event id>": {"block_kind": "shrine"|"pool"|"none", "joint_npcs": n, "npc_max": n,
                    "joint_mask": bits, "cloth": "ITM_CLOTH020"|"",
                    "maps": [[{"actor": "SP_NPC_EV_HANABI_0", "unit": [x, z]}, …], …]}}

`maps` has one entry per pond variant (`mFI_GetPuleIdx`) for pond events, else one.
Run: python3 tools/gen_event_map.py  (reads decomp_root from tools/config.local.json).
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from asset_pipeline.config import load_config  # noqa: E402

EVENT_IDS = [
    "fireworks_show",
    "cherry_blossom_festival",
    "sports_fair_foot_race",
    "sports_fair_aerobics",
    "sports_fair_ball_toss",
    "sports_fair_tug_of_war",
    "halloween",
    "new_years_day",
    "fishing_tourney_1",
    "fishing_tourney_2",
    "morning_aerobics",
    "harvest_moon_festival",
    "harvest_festival",
    "new_years_eve_countdown",
    "kamakura",
    "groundhog_day",
    "meteor_shower",
]

BLOCK_KINDS = {
    "mRF_BLOCKKIND_SHRINE": "shrine",
    "mRF_BLOCKKIND_POOL": "pool",
    "mRF_BLOCKKIND_NONE": "none",
}


def _array(text: str, name: str) -> str:
    m = re.search(r"\b%s\[\]\s*=\s*\{(.*?)\};" % re.escape(name), text, re.S)
    if not m:
        raise ValueError(name)
    return m.group(1)


def main() -> None:
    cfg = load_config()
    decomp = Path(cfg.decomp_root if hasattr(cfg, "decomp_root") else cfg["decomp_root"])
    text = (decomp / "src" / "game" / "m_event_map_npc_data.c_inc").read_text()
    text = re.sub(r"//[^\n]*", "", text)
    table = [t.strip().lstrip("&") for t in _array(text, "l_event_set_table").split(",") if t.strip()]
    out = {}
    for event_id, data_name in zip(EVENT_IDS, table):
        if data_name == "NULL":
            continue
        m = re.search(r"%s\s*=\s*\{([^}]*)\};" % re.escape(data_name), text)
        fields = [f.strip() for f in m.group(1).split(",")]
        _, joint, _map_max, npc_max, dt_table, npc_name, block_kind = fields
        npc = re.search(r"%s\s*=\s*\{([^}]*)\};" % re.escape(npc_name.lstrip("&")), text).group(1)
        mask_s, cloth = [f.strip() for f in npc.split(",")]
        maps = []
        for info_name in [t.strip().lstrip("&") for t in _array(text, dt_table).split(",") if t.strip()]:
            info = re.search(r"%s\s*=\s*\{([^}]*)\};" % re.escape(info_name), text).group(1)
            actors_name, pos_name = [f.strip() for f in info.split(",")]
            actors = [a.strip() for a in _array(text, actors_name).split(",") if a.strip()]
            units = re.findall(r"\{\s*(\d+)\s*,\s*(\d+)\s*\}", _array(text, pos_name))
            maps.append([
                {"actor": a, "unit": [int(x), int(z)]} for a, (x, z) in zip(actors, units)
            ])
        out[event_id] = {
            "block_kind": BLOCK_KINDS.get(block_kind, block_kind),
            "joint_npcs": int(joint),
            "npc_max": int(npc_max),
            "joint_mask": int(mask_s, 0),
            "cloth": "" if cloth == "EMPTY_NO" else cloth,
            "maps": maps,
        }
    dest = ROOT / "data" / "events" / "event_map.json"
    dest.write_text(json.dumps({
        "_comment": "Generated by tools/gen_event_map.py from m_event_map_npc_data.c_inc",
        "events": out,
    }, indent=1) + "\n")
    print("wrote", dest, len(out), "events")


if __name__ == "__main__":
    main()
